services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      # - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
